// South Korean Universities Database
const universities = [
  {
    id: 'snu',
    name: 'Seoul National University',
    nameMn: 'Сөүлийн Үндэсний Их Сургууль',
    nameKo: '서울대학교',
    type: 'university',
    logoText: 'SNU',
    logoBg: 'linear-gradient(135deg, #1e3a8a, #3b82f6)',
    location: 'Seoul',
    locationMn: 'Сөүл',
    locationKo: '서울',
    established: 1946,
    tuition: 3000000, // KRW per semester average
    scholarship: '30% - 100% (Based on TOPIK / GPA)',
    scholarshipMn: '30% - 100% (TOPIK болон GPA-аас хамаарна)',
    scholarshipKo: '30% - 100% (TOPIK / GPA 기준)',
    topikReq: 'Level 3+',
    topikReqMn: '3-р түвшин болон түүнээс дээш',
    topikReqKo: 'TOPIK 3급 이상',
    majors: ['Engineering', 'Business Administration', 'Social Sciences', 'Medicine'],
    majorsMn: ['Инженерчлэл', 'Бизнесийн удирдлага', 'Нийгмийн ухаан', 'Анагаах ухаан'],
    majorsKo: ['공과대학', '경영대학', '사회과학대학', '의과대학'],
    rating: 4.9,
    website: 'https://en.snu.ac.kr'
  },
  {
    id: 'yonsei',
    name: 'Yonsei University',
    nameMn: 'Ёнсей Их Сургууль',
    nameKo: '연세대학교',
    type: 'university',
    logoText: 'YU',
    logoBg: 'linear-gradient(135deg, #0b2265, #1d4ed8)',
    location: 'Seoul',
    locationMn: 'Сөүл',
    locationKo: '서울',
    established: 1885,
    tuition: 4200000,
    scholarship: 'Up to 100% for international students',
    scholarshipMn: 'Гадаад оюутнуудад 100% хүртэл тэтгэлэгтэй',
    scholarshipKo: '외국인 유학생 대상 최대 100% 장학금',
    topikReq: 'Level 3+ or IELTS 6.5',
    topikReqMn: '3-р түвшин эсвэл IELTS 6.5',
    topikReqKo: 'TOPIK 3급 이상 또는 IELTS 6.5',
    majors: ['Underwood International College', 'Global Leadership', 'Economics', 'Biotechnology'],
    majorsMn: ['Олон улсын сургууль', 'Глобал удирдлага', 'Эдийн засаг', 'Биотехнологи'],
    majorsKo: ['언더우드 국제대학', '글로벌인재대학', '경제학', '생명공학'],
    rating: 4.8,
    website: 'https://www.yonsei.ac.kr/en_sc/'
  },
  {
    id: 'korea',
    name: 'Korea University',
    nameMn: 'Корё Их Сургууль',
    nameKo: '고려대학교',
    type: 'university',
    logoText: 'KU',
    logoBg: 'linear-gradient(135deg, #7f1d1d, #ef4444)',
    location: 'Seoul',
    locationMn: 'Сөүл',
    locationKo: '서울',
    established: 1905,
    tuition: 4000000,
    scholarship: '30% - 100% Tuition Waiver',
    scholarshipMn: 'Сургалтын төлбөрөөс 30% - 100% хөнгөлнө',
    scholarshipKo: '등록금 30% - 100% 감면',
    topikReq: 'Level 3+ or TOEFL/IELTS',
    topikReqMn: '3-р түвшин эсвэл TOEFL/IELTS',
    topikReqKo: 'TOPIK 3급 이상 또는 TOEFL/IELTS',
    majors: ['Business Administration', 'Media & Communication', 'Computer Science', 'International Relations'],
    majorsMn: ['Бизнесийн удирдлага', 'Хэвлэл мэдээлэл & Харилцаа холбоо', 'Компьютерийн ухаан', 'Олон улсын харилцаа'],
    majorsKo: ['경영학과', '미디어학부', '컴퓨터학과', '국제학부'],
    rating: 4.8,
    website: 'https://www.korea.edu'
  },
  {
    id: 'kaist',
    name: 'KAIST',
    nameMn: 'КАИСТ (Шинжлэх Ухаан Технологийн Хүрээлэн)',
    nameKo: '카이스트 (한국과학기술원)',
    type: 'university',
    logoText: 'KST',
    logoBg: 'linear-gradient(135deg, #0284c7, #0f172a)',
    location: 'Daejeon',
    locationMn: 'Тэжон',
    locationKo: '대전',
    established: 1971,
    tuition: 3400000,
    scholarship: 'Full Tuition + Monthly Allowance (For almost all accepted students)',
    scholarshipMn: 'Бүрэн тэтгэлэг + Сар бүрийн тэтгэмж (Тэнцсэн бараг бүх оюутанд)',
    scholarshipKo: '학비 전액 지원 + 매월 생활비 보조 (합격자 대부분 지원)',
    topikReq: 'English Track (IELTS 6.5+ / TOEFL iBT 83+)',
    topikReqMn: 'Англи хэл дээр (IELTS 6.5+ эсвэл TOEFL iBT 83+)',
    topikReqKo: '영어 과정 (IELTS 6.5+ / TOEFL iBT 83+ 이상)',
    majors: ['Electrical Engineering', 'Computer Science', 'Mechanical Engineering', 'Physics'],
    majorsMn: ['Цахилгаан инженерчлэл', 'Компьютерийн ухаан', 'Механик инженерчлэл', 'Физик'],
    majorsKo: ['전기및전자공학부', '전산학부', '기계공학과', '물리학과'],
    rating: 4.9,
    website: 'https://www.kaist.ac.kr/en/'
  },
  {
    id: 'sogang',
    name: 'Sogang University',
    nameMn: 'Соган Их Сургууль',
    nameKo: '서강대학교',
    type: 'university',
    logoText: 'SU',
    logoBg: 'linear-gradient(135deg, #991b1b, #f43f5e)',
    location: 'Seoul',
    locationMn: 'Сөүл',
    locationKo: '서울',
    established: 1960,
    tuition: 3800000,
    scholarship: '25% - 100% Merit Scholarship',
    scholarshipMn: 'Сурлагын амжилтаар 25% - 100% тэтгэлэг',
    scholarshipKo: '성적 우수 장학금 25% - 100%',
    topikReq: 'Level 3+',
    topikReqMn: '3-р түвшин болон түүнээс дээш',
    topikReqKo: 'TOPIK 3급 이상',
    majors: ['Communication', 'Art & Technology', 'Global Korean Studies', 'Economics'],
    majorsMn: ['Харилцаа холбоо', 'Урлаг & Технологи', 'Глобал Солонгос судлал', 'Эдийн засаг'],
    majorsKo: ['커뮤니케이션학', '아트&테크놀로지학과', '글로벌한국학', '경제학과'],
    rating: 4.7,
    website: 'https://wwwe.sogang.ac.kr/wwwe/index.do'
  },
  {
    id: 'cau',
    name: 'Chung-Ang University',
    nameMn: 'Чун-Ан Их Сургууль',
    nameKo: '중앙대학교',
    type: 'university',
    logoText: 'CAU',
    logoBg: 'linear-gradient(135deg, #1e40af, #06b6d4)',
    location: 'Seoul',
    locationMn: 'Сөүл',
    locationKo: '서울',
    established: 1918,
    tuition: 3600000,
    scholarship: '50% - 100% based on TOPIK 5+',
    scholarshipMn: 'TOPIK 5+ түвшинтэй бол 50% - 100% тэтгэлэгтэй',
    scholarshipKo: 'TOPIK 5급 이상 취득 시 50% - 100% 장학금',
    topikReq: 'Level 3+ (Level 4+ for graduation)',
    topikReqMn: '3-р түвшин (Төгсөхөд 4-р түвшин шаардлагатай)',
    topikReqKo: 'TOPIK 3급 이상 (졸업 시 4급 필요)',
    majors: ['Pharmacy', 'Media & Communication', 'Business & Economics', 'Theater & Film'],
    majorsMn: ['Эмийн сан', 'Хэвлэл мэдээлэл & Харилцаа холбоо', 'Бизнес & Эдийн засаг', 'Театр & Кино урлаг'],
    majorsKo: ['약학부', '미디어커뮤니케이션학부', '경영경제대학', '연극영화과'],
    rating: 4.6,
    website: 'https://neweng.cau.ac.kr/index.do'
  },
  {
    id: 'pnu',
    name: 'Pusan National University',
    nameMn: 'Пүсаны Үндэсний Их Сургууль',
    nameKo: '부산대학교',
    type: 'university',
    logoText: 'PNU',
    logoBg: 'linear-gradient(135deg, #1e3a8a, #dc2626)',
    location: 'Busan',
    locationMn: 'Пүсан',
    locationKo: '부산',
    established: 1946,
    tuition: 2200000,
    scholarship: 'National and alumni scholarships (up to 100%)',
    scholarshipMn: 'Үндэсний болон төгсөгчдийн тэтгэлэг (100% хүртэл)',
    scholarshipKo: '국가 및 동문 장학금 (최대 100%)',
    topikReq: 'Level 3+',
    topikReqMn: '3-р түвшин болон түүнээс дээш',
    topikReqKo: 'TOPIK 3급 이상',
    majors: ['Oceanography', 'Mechanical Engineering', 'International Studies', 'Business'],
    majorsMn: ['Далай судлал', 'Механик инженерчлэл', 'Олон улсын судлал', 'Бизнес'],
    majorsKo: ['해양과학과', '기계공학부', '국제학부', '경영학과'],
    rating: 4.7,
    website: 'https://www.pusan.ac.kr/eng/Main.do'
  },
  {
    id: 'snu_lang',
    name: 'Seoul National University (Language Education)',
    nameMn: 'Сөүлийн Үндэсний Их Сургууль (Хэлний бэлтгэл)',
    nameKo: '서울대학교 언어교육원',
    type: 'language',
    logoText: 'SNUL',
    logoBg: 'linear-gradient(135deg, #3b82f6, #1d4ed8)',
    location: 'Seoul',
    locationMn: 'Сөүл',
    locationKo: '서울',
    established: 1963,
    tuition: 1730000, // per 10-week term
    scholarship: 'Excellent student awards (10% - 30% discount)',
    scholarshipMn: 'Шилдэг суралцагчийн шагнал (10% - 30% хөнгөлөлт)',
    scholarshipKo: '우수학생 포상 (10% - 30% 감면)',
    topikReq: 'No TOPIK required (Absolute Beginner to Advanced)',
    topikReqMn: 'TOPIK шаардлагагүй (Анхан шатнаас гүнзгий шат хүртэл)',
    topikReqKo: 'TOPIK 필요 없음 (기초부터 고급 과정까지)',
    majors: ['Korean Language Intensive (Level 1-6)', 'Korean Culture Activities'],
    majorsMn: ['Солонгос хэлний эрчимжүүлсэн курс (1-6 түвшин)', 'Солонгос соёлын хөтөлбөр'],
    majorsKo: ['한국어 집중 과정 (1-6급)', '한국 문화 체험 활동'],
    rating: 4.8,
    website: 'https://lei.snu.ac.kr/mobile/en/klec/main/main.jsp'
  },
  {
    id: 'ewha_lang',
    name: 'Ewha Womans University (Language Center)',
    nameMn: 'Ихва Охидын Их Сургууль (Хэлний бэлтгэл)',
    nameKo: '이화여자대학교 언어교육원',
    type: 'language',
    logoText: 'EWHL',
    logoBg: 'linear-gradient(135deg, #065f46, #10b981)',
    location: 'Seoul',
    locationMn: 'Сөүл',
    locationKo: '서울',
    established: 1962,
    tuition: 1600000, // per term
    scholarship: 'Academic encouragement scholarship',
    scholarshipMn: 'Сурлагыг дэмжих тэтгэлэг',
    scholarshipKo: '학업 장려 장학금',
    topikReq: 'No TOPIK required',
    topikReqMn: 'TOPIK шаардлагагүй',
    topikReqKo: 'TOPIK 필요 없음',
    majors: ['Intensive Korean Program', 'Short-term Program', 'Business Korean'],
    majorsMn: ['Эрчимжүүлсэн Солонгос хэлний хөтөлбөр', 'Богино хугацааны хөтөлбөр', 'Бизнес Солонгос хэл'],
    majorsKo: ['한국어 집중 과정', '단기 과정', '비즈니스 한국어 과정'],
    rating: 4.6,
    website: 'http://elc.ewha.ac.kr/elcen/main.asp'
  },
  {
    id: 'sogang_lang',
    name: 'Sogang University (Korean Language Education Center)',
    nameMn: 'Соган Их Сургууль (Солонгос хэлний төв)',
    nameKo: '서강대학교 한국어교육원',
    type: 'language',
    logoText: 'SGL',
    logoBg: 'linear-gradient(135deg, #be123c, #fda4af)',
    location: 'Seoul',
    locationMn: 'Сөүл',
    locationKo: '서울',
    established: 1990,
    tuition: 1790000,
    scholarship: 'Academic Excellence awards',
    scholarshipMn: 'Сурлагын амжилтын шагнал',
    scholarshipKo: '성적 우수 포상 장학금',
    topikReq: 'No TOPIK required (Highly speaking-focused)',
    topikReqMn: 'TOPIK шаардлагагүй (Ярианы дадлагад суурилсан)',
    topikReqKo: 'TOPIK 필요 없음 (말하기 집중 훈련 과정)',
    majors: ['Korean Language Education (Levels 1-6)', 'Speaking-focused program'],
    majorsMn: ['Солонгос хэлний боловсрол (1-6 түвшин)', 'Ярианд суурилсан эрчимжүүлсэн хөтөлбөр'],
    majorsKo: ['한국어 정규 과정 (1-6급)', '말하기 중심 한국어 과정'],
    rating: 4.7,
    website: 'https://klec.sogang.ac.kr'
  }
];

// Exporting to window object to be accessible by other scripts
window.universitiesDatabase = universities;
